import { BulkProductionImport, CreateProduction, Loom, Quality, Worker, WorkerCredentails } from "@/store";
import { api } from "./client";

export const login = (credentials: WorkerCredentails) => api.post('/auth/login', credentials)
export const creatWorker = (worker: Worker)=> api.post('/workers', worker)
export const getWorkers = ()=> api.get('/workers')
export const deleteWorker = (id: string)=> api.delete(`/workers/${id}`)
export const updateWorker = (id: string, worker: Partial<Worker>)=> api.put(`/workers/${id}`,worker)
export const createQuality = (credentials: Quality) => api.post('/qualities', credentials)
export const getAllQualities = ()=> api.get('/qualities')
export const createLoom = (credentials: Loom) => api.post('/looms', credentials)
export const getLooms = () => api.get('/looms')
export const deleteLooms = (id: string) => api.delete(`/looms/${id}`)
export const updateLooms = (id: string, loom: Partial<Loom>) => api.put(`/looms/${id}`, loom)
export const createProduction = (credentials: CreateProduction) => api.post('/production', credentials)
export const createProductionBulk = (credentials: BulkProductionImport) => api.post('/production/bulk', credentials)
export const getListProduction = (filters?: { date: string; loomId: string; operatorId: string; }) => api.get('/production')
export const getDailyLoomsReport = (date: string)=> api.get('/reports/daily-looms', { params: { date } })
export const getDailyQualityReport = (date: string) => api.get('/reports/daily-quality', { params: { date } })
export const getOperatorPeriodReport = (operatorId: string, from: string, to: string) => api.get('/reports/operator-period', { params: { operatorId, from, to } })
export const getPayrunReport = (from: string, to: string, commit?: boolean) => api.get('/reports/payrun', { params: { from, to, commit } })
export const get15DayOperatorReport = (operatorId: string, startDate: string) => api.get('/reports/15day-operator', { params: { operatorId, startDate } })
export const getBeamsReport = (dateFrom: string, dateTo: string, loomId?: string) => api.get('/beams/report', { params: { dateFrom, dateTo, ...(loomId && { loomId })  } })
export const getAllFactories = () => api.get('/factories')
